### ISSUE TITLE
Problem installation : DB Error: no such table

### ISSUE THREAD

**Issue by wyde22** [systopia/de.systopia.identitytracker#19]
Hi,

When i want to install this extension i have an error : `DB Error: no such table`. Here my log in civicrm :

```
sept. 19 11:19:15  [error] 
$Fatal Error Details = array:3 [
  "message" => "DB Error: no such table"
  "code" => null
  "exception" => CRM_Core_Exception {#10349
    -errorData: array:8 [
      "error_code" => -18
      "sql" => "        );"
      "debug_info" => """
        \n
              INSERT INTO `civicrm_value_contact_id_history` (`entity_id`, `identifier_type`, `identifier`, `used_since`)\n
                (SELECT  id AS ch_entity_id,\n
                         'internal' AS ch_type,\n
                         CAST(`id` AS CHAR) AS ch_indentifier,\n
                         COALESCE (DATE(`created_date`), DATE('2023-08-09 17:28:40')) AS ch_date\n
                  FROM   `civicrm_contact`\n
                  WHERE  `id` IS NOT NULL\n
                    AND  CAST(`id` AS CHAR) != ''\n
                    AND  NOT EXISTS ( SELECT `civicrm_value_contact_id_history`.`id` FROM `civicrm_value_contact_id_history`\n
                                       WHERE `entity_id` = `civicrm_contact`.`id`\n
                                         AND `identifier_type` = 'internal'\n
                                         AND `identifier` = `civicrm_contact`.`id`)\n
                ); [nativecode=1146 ** Table 'cerclealgerianis.civicrm_value_contact_id_history' doesn't exist]
        """
      "entity" => "Extension"
      "action" => "install"
      "is_error" => 1
      "error_message" => "DB Error: no such table"
      "debug_information" => "        );"
    ]
    #cause: null
    -_trace: null
    #message: "DB Error: no such table"
    #code: -18
    #file: "/var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/api/api.php"
    #line: 135
    trace: {
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/api/api.php:135 {
        civicrm_api3(string $entity, string $action, array $params = [])
        › if (is_array($result) && !empty($result['is_error'])) {
        ›   throw new CRM_Core_Exception($result['error_message'], CRM_Utils_Array::value('error_code', $result, 'undefined'), $result);
        › }
      }
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php:187 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php:624 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php:144 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php:43 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php:203 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php:103 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php:355 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php:364 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php:170 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php:105 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:319 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:69 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:36 { …}
      /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm.php:1199 { …}
      /var/aegir/platforms/wordpress/wp-includes/class-wp-hook.php:310 { …}
      /var/aegir/platforms/wordpress/wp-includes/class-wp-hook.php:334 { …}
      /var/aegir/platforms/wordpress/wp-includes/plugin.php:517 { …}
      /var/aegir/platforms/wordpress/wp-admin/admin.php:259 { …}
    }
  }
]


sept. 19 11:19:15  [debug] $backTrace = #0 /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(443): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(CRM_Core_Exception))
#2 /var/aegir/platforms/wordpress/wp-content/plugins/civicrm/civicrm.php(1199): CRM_Core_Invoke::invoke((Array:3))
#3 /var/aegir/platforms/wordpress/wp-includes/class-wp-hook.php(310): CiviCRM_For_WordPress->invoke("")
#4 /var/aegir/platforms/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters("", (Array:1))
#5 /var/aegir/platforms/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action((Array:1))
#6 /var/aegir/platforms/wordpress/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#7 {main}
```

**Comment by wyde22** [comment]
Hi,

Do you have a solution for this issue please ? :)

Thanks

**Comment by BrutalBirdie** [comment]
Same problem with the `civicrm_value_contact_id_history` table which does not exist an thus failing.

EDIT: noticed the system I am working on has the version `1.4-dev` will try the `1.3.1` release and report back.

**Comment by bjendres** [comment]
What CiviCRM version are you on? (ping @jensschuppe)

**Comment by bjendres** [comment]
~~This problem appears when the installer doesn't run the ``auto_install.sql`` script.~~

**Comment by BrutalBirdie** [comment]
this is odd.
I just run:
```
wget https://github.com/systopia/de.systopia.identitytracker/releases/download/1.3.1/de.systopia.identitytracker-1.3.1.zip
unzip de.systopia.identitytracker-1.3.1.zip; rm de.systopia.identitytracker-1.3.1.zip
cv en de.systopia.identitytracker
```
and get:
```
Enabling extension "de.systopia.identitytracker"
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294

In mysqli.php line 872:
                                                                                          
  mysqli_real_escape_string(): Argument #2 ($string) must be of type string, array given  
                                                                                          

ext:enable [-r|--refresh] [--ignore-missing] [--level LEVEL] [--hostname HOSTNAME] [-t|--test] [-U|--user USER] [--] [<key-or-name>...]
```

might not be related to this issue in particular. 🤔

**Comment by BrutalBirdie** [comment]
> This problem appears when the installer doesn't run the `auto_install.sql` script.

Which `auto_install.sql`? There is no `auto_install.sql` file in this repository.
I know that funding has such a file => https://github.com/systopia/funding/blob/main/sql/auto_install.sql which also does not include the table in question `civicrm_value_contact_id_history` on the main branch at least.

Further searching:

https://github.com/search?q=org%3Asystopia+auto_install.sql+language%3ASQL&type=code&l=SQL 

https://github.com/search?q=org%3Asystopia+civicrm_value_contact_id_history&type=code

**Comment by bjendres** [comment]
> Which `auto_install.sql`? There is no `auto_install.sql` file in this repository. 

Yes sorry, I was confusing this with a similar issue we had with another extension.

The table should be created using managed entities (https://github.com/systopia/de.systopia.identitytracker/blob/master/managed/CustomGroup__contact_id_history.mgd.php), and that doesn't seem to be working in some cases.

Please try to uninstall the extension and then try installing the version from ``master``.

May I ask again which CiviCRM version you're running?

**Comment by BrutalBirdie** [comment]
Ehm.. I am just tinkering on a CiviCRM that was thrown at me since `funding` could not be installed 😬 I try to find the version.
And I will try your suggested solution.
be right back 👋🏻

**Comment by BrutalBirdie** [comment]
Drupal 10.1.5

excerpt from `package.json`
```
        "civicrm/civicrm-core": "^5.63.1",
        "civicrm/civicrm-drupal-8": "^5.63.1",
        "civicrm/civicrm-packages": "^5.63.1",
        "drupal/civicrm_entity": "^4.0@alpha",
```
footer states `Powered by CiviCRM 5.65.2, free and open source AGPLv3 software.`

**Comment by BrutalBirdie** [comment]
Did:
```
cv ext:uninstall de.systopia.identitytracker
```
and then

```
cv en de.systopia.identitytracker
Enabling extension "de.systopia.identitytracker"
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
Error: API Call Failed: Array
(
    [entity] => Extension
    [action] => install
    [params] => Array
        (
            [keys] => Array
                (
                    [0] => de.systopia.identitytracker
                )

            [debug] => 1
            [version] => 3
        )

    [result] => Array
        (
            [trace] => #0 /app/code/vendor/pear/db/DB/mysqli.php(403): mysqli_query()
#1 /app/code/vendor/pear/db/DB/common.php(1219): DB_mysqli->simpleQuery()
#2 /app/code/vendor/civicrm/civicrm-packages/DB/DataObject.php(2696): DB_common->query()
#3 /app/code/vendor/civicrm/civicrm-packages/DB/DataObject.php(1829): DB_DataObject->_query()
#4 /app/code/vendor/civicrm/civicrm-core/CRM/Core/DAO.php(487): DB_DataObject->query()
#5 /app/code/vendor/civicrm/civicrm-core/CRM/Core/DAO.php(1650): CRM_Core_DAO->query()
#6 /app/data/default/files/civicrm/ext/de.systopia.identitytracker_old/CRM/Identitytracker/Migration.php(56): CRM_Core_DAO::executeQuery()
#7 /app/data/default/files/civicrm/ext/de.systopia.identitytracker_old/CRM/Identitytracker/Migration.php(22): CRM_Identitytracker_Migration::migrate()
#8 /app/data/default/files/civicrm/ext/de.systopia.identitytracker_old/identitytracker.php(102): CRM_Identitytracker_Migration::migrateInternal()
#9 /app/code/vendor/civicrm/civicrm-core/CRM/Extension/Manager/Module.php(70): identitytracker_civicrm_enable()
#10 /app/code/vendor/civicrm/civicrm-core/CRM/Extension/Manager/Module.php(39): CRM_Extension_Manager_Module->callHook()
#11 /app/code/vendor/civicrm/civicrm-core/CRM/Extension/Manager.php(296): CRM_Extension_Manager_Module->onPreInstall()
#12 /app/code/vendor/civicrm/civicrm-core/api/v3/Extension.php(42): CRM_Extension_Manager->install()
#13 /app/code/vendor/civicrm/civicrm-core/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_extension_install()
#14 /app/code/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(158): Civi\API\Provider\MagicFunctionProvider->invoke()
#15 /app/code/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest()
#16 /app/code/vendor/civicrm/civicrm-core/api/api.php(22): Civi\API\Kernel->runSafe()
#17 phar:///usr/local/bin/cv/src/Command/BaseCommand.php(39): civicrm_api()
#18 phar:///usr/local/bin/cv/src/Command/ExtensionEnableCommand.php(68): Civi\Cv\Command\BaseCommand->callApiSuccess()
#19 phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php(127): Civi\Cv\Command\ExtensionEnableCommand->execute()
#20 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(637): Cvphar\Symfony\Component\Console\Command\Command->run()
#21 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(190): Cvphar\Symfony\Component\Console\Application->doRunCommand()
#22 phar:///usr/local/bin/cv/src/Application.php(67): Cvphar\Symfony\Component\Console\Application->doRun()
#23 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(101): Civi\Cv\Application->doRun()
#24 phar:///usr/local/bin/cv/src/Application.php(33): Cvphar\Symfony\Component\Console\Application->run()
#25 phar:///usr/local/bin/cv/bin/cv(28): Civi\Cv\Application::main()
#26 /usr/local/bin/cv(14): require('...')
#27 {main}
            [is_error] => 1
            [error_message] => Unknown column 'identifier_type' in 'field list'
        )

)
```

`de.systopia.identitytracker` git info commit `1c8f20c249983affeed5445ef401fc84730a16f4` so latest changes from master.

**Comment by bjendres** [comment]
hm, maybe you can do some debugging with @dontub tomorrow.

**Comment by BrutalBirdie** [comment]
Sure! Happy to provide help.
I will check my github notifications tomorrow even more ;)
Also my mail and matrix are public on my github profile.

**Comment by jensschuppe** [comment]
The problem might be due to the extension not using the CiviCRM API for `INSERT`ing values, but issues an SQL query with the raw `table_name` (which does not include the prefix). If you have table name prefixes configured in `civicrm.settings.php`, MySQL will fail with `No such table`.

With this being said, the extension used to ignore table prefixes. This has now become visible with custom fields being defined a managed entities (which do utilize table prefixes).

The extension should use the API for setting values, etc. instead of SQL queries.

**Comment by dontub** [comment]
> ```
> In mysqli.php line 872:
>                                                                                           
>   mysqli_real_escape_string(): Argument #2 ($string) must be of type string, array given  
> ```

This is fixed by #14. @BrutalBirdie

**Comment by BrutalBirdie** [comment]
> > ```
> > In mysqli.php line 872:
> >                                                                                           
> >   mysqli_real_escape_string(): Argument #2 ($string) must be of type string, array given  
> > ```
> 
> This is fixed by #14. @BrutalBirdie

Yes this was on the outdated version, on the master branch its
 `[error_message] => Unknown column 'identifier_type' in 'field list'`

**Comment by BrutalBirdie** [comment]
@dontub that is not the current error that you quoted.
The issue persists.

**Comment by jensschuppe** [comment]
@BrutalBirdie Could you show us your `civicrm_value_contact_id_history` (maybe the name is prefixed on your install) table definition? Seems that table is broken on your installation.

**Comment by BrutalBirdie** [comment]
@jensschuppe 
```
mysql> DESCRIBE civicrm_value_contact_id_history;
+-----------+--------------+------+-----+---------+----------------+
| Field     | Type         | Null | Key | Default | Extra          |
+-----------+--------------+------+-----+---------+----------------+
| id        | int unsigned | NO   | PRI | NULL    | auto_increment |
| entity_id | int unsigned | NO   | MUL | NULL    |                |
+-----------+--------------+------+-----+---------+----------------+
2 rows in set (0.01 sec)
```

**Comment by wyde22** [comment]
Hi,

I have this version of CiviCRM 5.65.1 and the version of my WordPress is 6.3.1

I can see the version of Contact Identity Tracker : 1.4-dev. It's necessary to use the master `branch ` ?

Thanks

**Comment by jensschuppe** [comment]
> @jensschuppe
> 
> ```
> mysql> DESCRIBE civicrm_value_contact_id_history;
> +-----------+--------------+------+-----+---------+----------------+
> | Field     | Type         | Null | Key | Default | Extra          |
> +-----------+--------------+------+-----+---------+----------------+
> | id        | int unsigned | NO   | PRI | NULL    | auto_increment |
> | entity_id | int unsigned | NO   | MUL | NULL    |                |
> +-----------+--------------+------+-----+---------+----------------+
> 2 rows in set (0.01 sec)
> ```

@BrutalBirdie The table is missing all custom field columns. Could you try running a `Managed.reconcile` API4 call (`civicrm/api4#/explorer/Managed/reconcile?modules="%5Bde.systopia.identitytracker%5D"`) to see why they weren't created?

**Comment by jensschuppe** [comment]
> I can see the version of Contact Identity Tracker : 1.4-dev. It's necessary to use the master branch  ?

@wyde22 If there's no specific reason to use the `1.4` version branch (on the `master` branch), you might want to use the latest stable release, which is `1.3.1`. `1.4` is still in alpha.

**Comment by BrutalBirdie** [comment]
> > @jensschuppe
> > ```
> > mysql> DESCRIBE civicrm_value_contact_id_history;
> > +-----------+--------------+------+-----+---------+----------------+
> > | Field     | Type         | Null | Key | Default | Extra          |
> > +-----------+--------------+------+-----+---------+----------------+
> > | id        | int unsigned | NO   | PRI | NULL    | auto_increment |
> > | entity_id | int unsigned | NO   | MUL | NULL    |                |
> > +-----------+--------------+------+-----+---------+----------------+
> > 2 rows in set (0.01 sec)
> > ```
> 
> @BrutalBirdie The table is missing all custom field columns. Could you try running a `Managed.reconcile` API4 call (`civicrm/api4#/explorer/Managed/reconcile?modules="%5Bde.systopia.identitytracker%5D"`) to see why they weren't created?

```bash
cv api4 Managed.reconcile
[]
```

😬

**Comment by jensschuppe** [comment]
> ```shell
> cv api4 Managed.reconcile
> []
> ```  
> 😬

So, what does the table look like now? Are there any errors in the logs? If there's still an issue, try uninstalling and re-installing the extension. And same advice here: if there's no explicit need for the currently-alpha branch of `1.4`, please use the latest stable version `1.3.1`.

**Comment by BrutalBirdie** [comment]
@jensschuppe let me do a full log of what I am doing right now.

the module is in `sites/default/files/civicrm/ext/de.systopia.identitytracker` and downloaded via `git clone`
The current version is now: `git log`:

```
commit 72b56e00b27372ff68c5c0f29438f1cbb5e7e8c9 (HEAD, tag: 1.3.1, origin/1.3.x)
Author: B. Endres <endres@systopia.de>
Date:   Thu Sep 21 12:03:30 2023 +0200

    released 1.3.1
```

Now I try to install / enable the extension from the `ext` folder:

```
cv ext:install de.systopia.identitytracker
Enabling extension "de.systopia.identitytracker"
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
[PHP Deprecation] Function strftime() is deprecated at /app/code/vendor/pear/log/Log/file.php:294
Error: API Call Failed: Array
(
    [entity] => Extension
    [action] => install
    [params] => Array
        (
            [keys] => Array
                (
                    [0] => de.systopia.identitytracker
                )

            [debug] => 1
            [version] => 3
        )

    [result] => Array
        (
            [trace] => #0 /app/code/vendor/pear/db/DB/mysqli.php(403): mysqli_query()
#1 /app/code/vendor/pear/db/DB/common.php(1219): DB_mysqli->simpleQuery()
#2 /app/code/vendor/civicrm/civicrm-packages/DB/DataObject.php(2696): DB_common->query()
#3 /app/code/vendor/civicrm/civicrm-packages/DB/DataObject.php(1829): DB_DataObject->_query()
#4 /app/code/vendor/civicrm/civicrm-core/CRM/Core/DAO.php(487): DB_DataObject->query()
#5 /app/code/vendor/civicrm/civicrm-core/CRM/Core/DAO.php(1650): CRM_Core_DAO->query()
#6 /app/data/default/files/civicrm/ext/de.systopia.identitytracker_old/CRM/Identitytracker/Migration.php(56): CRM_Core_DAO::executeQuery()
#7 /app/data/default/files/civicrm/ext/de.systopia.identitytracker_old/CRM/Identitytracker/Migration.php(22): CRM_Identitytracker_Migration::migrate()
#8 /app/data/default/files/civicrm/ext/de.systopia.identitytracker_old/identitytracker.php(102): CRM_Identitytracker_Migration::migrateInternal()
#9 /app/code/vendor/civicrm/civicrm-core/CRM/Extension/Manager/Module.php(70): identitytracker_civicrm_enable()
#10 /app/code/vendor/civicrm/civicrm-core/CRM/Extension/Manager/Module.php(39): CRM_Extension_Manager_Module->callHook()
#11 /app/code/vendor/civicrm/civicrm-core/CRM/Extension/Manager.php(296): CRM_Extension_Manager_Module->onPreInstall()
#12 /app/code/vendor/civicrm/civicrm-core/api/v3/Extension.php(42): CRM_Extension_Manager->install()
#13 /app/code/vendor/civicrm/civicrm-core/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_extension_install()
#14 /app/code/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(158): Civi\API\Provider\MagicFunctionProvider->invoke()
#15 /app/code/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest()
#16 /app/code/vendor/civicrm/civicrm-core/api/api.php(22): Civi\API\Kernel->runSafe()
#17 phar:///usr/local/bin/cv/src/Command/BaseCommand.php(39): civicrm_api()
#18 phar:///usr/local/bin/cv/src/Command/ExtensionEnableCommand.php(68): Civi\Cv\Command\BaseCommand->callApiSuccess()
#19 phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php(127): Civi\Cv\Command\ExtensionEnableCommand->execute()
#20 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(637): Cvphar\Symfony\Component\Console\Command\Command->run()
#21 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(190): Cvphar\Symfony\Component\Console\Application->doRunCommand()
#22 phar:///usr/local/bin/cv/src/Application.php(67): Cvphar\Symfony\Component\Console\Application->doRun()
#23 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(101): Civi\Cv\Application->doRun()
#24 phar:///usr/local/bin/cv/src/Application.php(33): Cvphar\Symfony\Component\Console\Application->run()
#25 phar:///usr/local/bin/cv/bin/cv(28): Civi\Cv\Application::main()
#26 /usr/local/bin/cv(14): require('...')
#27 {main}
            [is_error] => 1
            [error_message] => Unknown column 'identifier_type' in 'field list'
        )

)
```

I run:
```
cv api4 Managed.reconcile modules='["de.systopia.identitytracker"]'
[]
```
Check the DB table:
```
mysql> DESCRIBE civicrm_value_contact_id_history;
+-----------+--------------+------+-----+---------+----------------+
| Field     | Type         | Null | Key | Default | Extra          |
+-----------+--------------+------+-----+---------+----------------+
| id        | int unsigned | NO   | PRI | NULL    | auto_increment |
| entity_id | int unsigned | NO   | MUL | NULL    |                |
+-----------+--------------+------+-----+---------+----------------+
2 rows in set (0.00 sec)
```

Do an uninstall and reinstall and still same issue.


Just do be 100% sure I will do a complete fresh setup of drupal with civicrm to check if my existing setup has some historic issues.

**Comment by jensschuppe** [comment]
The `1.3.1` version does not utilize managed entities for creating custom fields, so if you're having issues while installing that version, `Managed.reconcile` won't help.

I'm quite sure uninstalling does not attempt to remove the custom fields the extension created (or tried to in your case). You might have to manually remove the custom fields and custom group (via the Custom Fields UI) before re-installing, maybe even by removing database tables manually. Otherwise, the extension will not re-create them when being re-installed.

**Comment by BrutalBirdie** [comment]
When using the `1.3.1` release /  tag the error which was fixed in #14 is not included in the `1.3.1` release.
And there is no other stable release which included this fix.

So go inside the `de.systopia.identitytracker` which is on tag `1.3.1`:
```bash
wget https://github.com/systopia/de.systopia.identitytracker/pull/14.patch
git apply 14.patch
rm 14.patch
```

Enable:
```bash
cv en de.systopia.identitytracker
```
No error.

Table?
```
mysql> DESCRIBE civicrm_value_contact_id_history;
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | int unsigned | NO   | PRI | NULL    | auto_increment |
| entity_id       | int unsigned | NO   | MUL | NULL    |                |
| identifier_type | varchar(255) | YES  | MUL | NULL    |                |
| identifier      | varchar(255) | YES  | MUL | NULL    |                |
| used_since      | datetime     | YES  | MUL | NULL    |                |
+-----------------+--------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```

Now I will add all other extensions needed one after another with the latest stable version (if present) from github.

**Comment by BrutalBirdie** [comment]
Now [de.systopia.remotetools](https://github.com/systopia/de.systopia.remotetools) is throwing errors.
```
cv en de.systopia.remotetools
Extension cache does not contain requested item(s)
Refreshing extension cache
Enabling extension "de.systopia.remotetools"

In RemoteToolsRequest.php line 29:
                                                             
  Class "Symfony\Component\EventDispatcher\Event" not found  
                                                             

ext:enable [-r|--refresh] [--ignore-missing] [--level LEVEL] [--hostname HOSTNAME] [-t|--test] [-U|--user USER] [--] [<key-or-name>...]
```
for the remotetools I checked out the 0.5.0 release.

**Comment by BrutalBirdie** [comment]
This would be fixed by https://github.com/systopia/de.systopia.remotetools/pull/18 where I just applied the suggested fix from the issue.

But this does not result in a working state.

Since the `funding` ext does throw this error when trying to interact throws the following drupal error:
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "Civi\Funding\Api4\Action\FundingProgram\GetFieldsAction". in Symfony\Component\DependencyInjection\Container::make() (line 264 of /app/code/vendor/symfony/dependency-injection/Container.php).
```

fyi: I am working with a Drupal 10 instance.

**Comment by dontub** [comment]
The funding extension currently depends on the `remote-tools-api4` branch of `de.systopia.remotetools`.

**Comment by BrutalBirdie** [comment]
> The funding extension currently depends on the `remote-tools-api4` branch of `de.systopia.remotetools`.

I switched the branch to the mentioned `remote-tools-api4` and installed the extension with no errors.
But the funding extension, still on version `0.8.0` main branch commit `a8944bcf83c8cdb5ab4b8e38f48f4f67bca15072`, when installing now states:

```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                                                                                        
  The service "Civi\Funding\Api4\Action\FundingApplicationProcessActivity\GetAction" has a dependency on a non-existent service "int". 
```
From `drush ws --extended`
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service                                     
                                          "Civi\Funding\Api4\Action\FundingApplicationProcessActivity\GetAction" has a dependency on a non-existent service "int".  
                                          in Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue() (line 86   
                                          of /app/code/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php).
                                          ```

**Comment by BrutalBirdie** [comment]
Since now this issue is spreading over to the `funding` module.
I will relay my issue over there with a fresh start and a clean issue.

**Comment by jensschuppe** [comment]
This seems to be happening because of raw SQL queries being used for migrating contact and external identifiers into this extension's data structure when installing/enabling, while managed entities are not guaranteed to be reconciled at this point, possibly due to transactions. So I'd say this can be fixed by using the API for those migrations instead of raw SQL queries.

**Comment by dontub** [comment]
Can the migration be performed in an upgrade step instead of [on enable](https://github.com/systopia/de.systopia.identitytracker/blob/b9d5ab12ac60b255f96a60efbe7af848e2c0271c/identitytracker.php#L102)? If not an alternative could be to check for field existence, e.g.:
```php
CustomField::get(FALSE)
  ->selectRowCount()
  ->addWhere('name', '=', CRM_Identitytracker_Configuration::TYPE_FIELD_NAME)
  ->addWhere('custom_group_id.name', '=', CRM_Identitytracker_Configuration::GROUP_NAME)
  ->execute()
  ->countMatched()
```

**Comment by bjendres** [comment]
> Can the migration be performed in an upgrade step instead of [on enable](https://github.com/systopia/de.systopia.identitytracker/blob/b9d5ab12ac60b255f96a60efbe7af848e2c0271c/identitytracker.php#L102)? If not an alternative could be to check for field existence, e.g.:

I'd prefer to **check for existence**, because I'm not how to find out what the right (static) status upgrade step ID would be - that might differ from case to case.

**Comment by jensschuppe** [comment]
> Can the migration be performed in an upgrade step instead of [on enable](https://github.com/systopia/de.systopia.identitytracker/blob/b9d5ab12ac60b255f96a60efbe7af848e2c0271c/identitytracker.php#L102)?

Migration needs to be done when installing (not necessarily enabling) the extension. Wouldn't it be enough to migrate using the API to not try to write to the table before the *Managed Entity* transaction for creating it is committed?

**Comment by bjendres** [comment]
> Migration needs to be done when installing (not necessarily enabling) the extension

I disagree, it could be a simple upgrader step (adjusting the extensions' schema version) that would have to run before the extension itself is used. Just like with any other extension upgrade, it would pop up offering to run the migration.

**Comment by jensschuppe** [comment]
We're talking about "migrating" CiviCRM contact ID and external identifier into Identity Tracker records when installing the extension, aren't we? Those have been processed when enabling the extension and should carry on doing so, right? This should not be done in an upgrade step.

**Comment by bjendres** [comment]
> We're talking about "migrating" CiviCRM contact ID and external identifier into Identity Tracker records when installing the extension, aren't we? 

Yes, maybe I misunderstood. Just make sure this process works for upgrades as well as for new installations.
